### ISSUE TITLE
Can't install package form npm

### ISSUE THREAD

**Issue by zhanguangao** [derektu/react-native-bluetooth-serial#1]
I can't install package form npm, because of 'https://github.com/rusel1989/react-native-bluetooth-serial' is the same as installing method commond.

**Comment by timscott** [comment]
On npm react-native-bluetooth-serial is this:
https://github.com/rusel1989/react-native-bluetooth-serial

Not this:
https://github.com/derektu/react-native-bluetooth-serial

I guess we should us this one?
https://github.com/derektu/react-native-android-btserial

**Comment by derektu** [comment]
Due to personal reason, I won't be able to improve this project for the time being. So my suggestion is to use https://github.com/rusel1989/react-native-bluetooth-serial as currently listed in npm registry.

Sorry about that.
